import "server-only";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
import { loadTipRecipient } from "./recipient";

/**
 * Persists a settled Coinflow payment into the shop's local ledger so the Tips
 * page can roll it up. Called from the checkout success callback; idempotent on
 * cf_payment_id so a retry (or a webhook delivering later) can't double-count.
 */
export async function recordCheckoutPayment({
  shopId,
  submerchantId,
  orderTicket,
  subtotalCents,
  tipCents,
  totalCents,
  paymentMethod,
  cfPaymentId,
  settledAt = new Date(),
}: {
  shopId: string;
  submerchantId?: string;
  orderTicket: string;
  subtotalCents: number;
  tipCents: number;
  totalCents: number;
  paymentMethod: string;
  cfPaymentId: string;
  settledAt?: Date;
}): Promise<{ ok: true } | { ok: false; reason: string }> {
  const supabase = getSupabaseAdmin();
  const recipient = await loadTipRecipient({ shopId, submerchantId });
  if (!recipient) {
    return {
      ok: false,
      reason: `No tip recipient configured for shop ${shopId}; set TIP_RECIPIENT_CF_USER_ID and seed staff.`,
    };
  }

  // Business date is the shop's local day the sale closed on.
  const { data: shop } = await supabase.from("shops").select("timezone").eq("id", shopId).single();
  const timezone = shop?.timezone ?? "America/Los_Angeles";
  const businessDate = settledAt.toLocaleDateString("en-CA", { timeZone: timezone });

  // Deduplicate by cf_payment_id — webhook + onSuccess may race.
  const { data: existing } = await supabase
    .from("payments")
    .select("id,order_id")
    .eq("cf_payment_id", cfPaymentId)
    .maybeSingle();
  if (existing) return { ok: true };

  // orders.id is a UUID generated by Supabase; the client-side `orderId`
  // (e.g. "LMMUX1SPCU") is the human ticket number. Upsert on the composite
  // (shop_id, business_date, ticket_number) so a retry hits the same order row.
  const { data: order, error: orderErr } = await supabase
    .from("orders")
    .upsert(
      {
        shop_id: shopId,
        ticket_number: orderTicket,
        business_date: businessDate,
        server_id: recipient.staffId,
        status: "paid",
        subtotal_cents: subtotalCents,
      },
      { onConflict: "shop_id,business_date,ticket_number" },
    )
    .select("id")
    .single();
  if (orderErr || !order) {
    console.error("[tips] order upsert failed", orderErr);
    return { ok: false, reason: orderErr?.message ?? "Order upsert returned no row" };
  }

  const { error: payErr } = await supabase.from("payments").insert({
    order_id: order.id,
    shop_id: shopId,
    cf_payment_id: cfPaymentId,
    attempt: 1,
    status: "settled",
    method: paymentMethod,
    subtotal_cents: subtotalCents,
    tip_cents: tipCents,
    amount_cents: totalCents,
    settled_at: settledAt.toISOString(),
  });
  if (payErr) {
    console.error("[tips] payment insert failed", payErr);
    return { ok: false, reason: payErr.message };
  }

  return { ok: true };
}
