-- Logins for a sample of Adora locations. cf_submerchant_id stays null until
-- onboarding creates the Coinflow account. Password matches the demo login.
-- Existing emails, including any location already onboarded, are left alone.

insert into public.merchant_logins (email, name, password)
values
  ('chris+mmp-kjt3q@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-m74y6@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-87247@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-n9v93@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-jc3wy@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-np1tw@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-8pdq5@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-k9yr3@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-u9ztn@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-mqrwr@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-5w56m@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-9hw82@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-5alrn@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-kc3ed@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+mmp-lbxzb@coinflowlabs.app', 'Mountain Mike''s Pizza', '11111'),
  ('chris+marcos-lp86b4@coinflowlabs.app', 'Marco''s Pizza', '11111'),
  ('chris+marcos-lp899z@coinflowlabs.app', 'Marco''s Pizza', '11111'),
  ('chris+marcos-lpndr3@coinflowlabs.app', 'Marco''s Pizza', '11111'),
  ('chris+marcos-lp55lh@coinflowlabs.app', 'Marco''s Pizza', '11111'),
  ('chris+marcos-lpmxal@coinflowlabs.app', 'Marco''s Pizza', '11111'),
  ('chris+romeos-58vet@coinflowlabs.app', 'Romeo''s Pizza', '11111'),
  ('chris+romeos-m7xc1@coinflowlabs.app', 'Romeo''s Pizza', '11111'),
  ('chris+romeos-kt6b8@coinflowlabs.app', 'Romeo''s Pizza', '11111'),
  ('chris+romeos-8u9lx@coinflowlabs.app', 'Romeo''s Pizza', '11111'),
  ('chris+romeos-9tvsh@coinflowlabs.app', 'Romeo''s Pizza', '11111'),
  ('wu+pizzaguys-klgqm@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-5kqxl@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-myzyp@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-8nycc@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-5vzru@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-nuz2a@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-mvphy@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-muyu7@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-8lgc8@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+pizzaguys-kt62a@coinflowlabs.app', 'Pizza Guys', '11111'),
  ('wu+woodstocks-un57x@coinflowlabs.app', 'Woodstock''s Pizza', '11111'),
  ('wu+woodstocks-m8pvw@coinflowlabs.app', 'Woodstock''s Pizza', '11111'),
  ('wu+pizzamyheart-kqmtv@coinflowlabs.app', 'Pizza My Heart', '11111'),
  ('wu+pizzamyheart-mk95x@coinflowlabs.app', 'Pizza My Heart', '11111'),
  ('wu+pizzamyheart-lm8xh@coinflowlabs.app', 'Pizza My Heart', '11111'),
  ('wu+pizzamyheart-l1yqx@coinflowlabs.app', 'Pizza My Heart', '11111'),
  ('wu+pizzamyheart-j5rl5@coinflowlabs.app', 'Pizza My Heart', '11111'),
  ('wu+freshbrothers-8dku1@coinflowlabs.app', 'Fresh Brothers', '11111'),
  ('wu+freshbrothers-mq3dj@coinflowlabs.app', 'Fresh Brothers', '11111'),
  ('wu+freshbrothers-5x9sn@coinflowlabs.app', 'Fresh Brothers', '11111'),
  ('wu+freshbrothers-lxp8d@coinflowlabs.app', 'Fresh Brothers', '11111'),
  ('wu+freshbrothers-ljqt6@coinflowlabs.app', 'Fresh Brothers', '11111'),
  ('wu+toppers-mcjnw@coinflowlabs.app', 'Toppers Pizza', '11111'),
  ('wu+toppers-9sxaz@coinflowlabs.app', 'Toppers Pizza', '11111'),
  ('wu+toppers-5nl15@coinflowlabs.app', 'Toppers Pizza', '11111')
on conflict (email) do nothing;
